echo ""
echo "🔍 Verify deployment:"
echo "   curl https://erpnext-agent-gateway.workers.dev/health"
echo ""
echo "📊 Monitor logs:"
echo "   cd $AGENT_GATEWAY"
echo "   pnpm dlx wrangler tail erpnext-agent-gateway"
echo ""
echo "🎉 Your ERPNext Coagents are now live on Cloudflare!"
echo ""