# Fly.io configuration for ERPNext CoAgent
app = "erpnext-coagent"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  NODE_ENV = "production"
  PYTHONUNBUFFERED = "1"
  PORT = "8080"
  OPENROUTER_MODEL = "mistralai/mistral-7b-instruct"
  OPENROUTER_APP_TITLE = "ERPNext CoAgent Assistant"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
