# Wrangler configuration for Agent Gateway
name = "multi-industry-coagents-gateway"
account_id = "5a34e22d045e4ff3538a636317a631e8"
main = "src/worker.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"
GATEWAY_PORT = "3000"
GATEWAY_HOST = "0.0.0.0"

# KV namespace for session storage (replaces Redis)
[[kv_namespaces]]
binding = "SESSIONS"
id = "eec1ac4c36d14839a7574b41c0ffa339"

# KV namespace for workflow state
[[kv_namespaces]]
binding = "WORKFLOW_STATE"
id = "3733a35d182d4f58872db5f46c73aba5"

# D1 Database for workflow checkpoints
[[d1_databases]]
binding = "DB"
database_name = "erpnext-workflows-db"
database_id = "438122c1-fe33-446c-a222-4bb3cfeb8fa5"

# Cloudflare Workers AI binding (T146: Free tier AI models)
[ai]
binding = "AI"

# Secrets (set via: pnpm dlx wrangler secret put <NAME>)
# Environment variables required:
# - OPENROUTER_API_KEY (optional if using Cloudflare AI)
# - OPENROUTER_MODEL (optional)
# - OPENROUTER_BASE_URL (optional)
# - ERPNEXT_API_KEY
# - ERPNEXT_API_SECRET
# - ERPNEXT_BASE_URL
# - AI_PROVIDER (optional: 'openrouter' | 'cloudflare' | 'auto', default: 'auto')
# - CLOUDFLARE_MODEL (optional, default: '@cf/meta/llama-3.1-8b-instruct')
# - PREFER_FREE_TIER (optional: 'true' | 'false', default: 'false')

# Build configuration
[build]
command = "npm run build"

# Development
[dev]
port = 3000
