# Wrangler configuration for Agent Gateway
name = "erpnext-agent-gateway"
account_id = "5a34e22d045e4ff3538a636317a631e8"
main = "src/server.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NODE_ENV = "production"
GATEWAY_PORT = "3000"
GATEWAY_HOST = "0.0.0.0"

# KV namespace for session storage (replaces Redis)
[[kv_namespaces]]
binding = "SESSIONS"
id = "eec1ac4c36d14839a7574b41c0ffa339"

# Secrets (set via: pnpm dlx wrangler secret put <NAME>)
# Environment variables required:
# - OPENROUTER_API_KEY
# - OPENROUTER_MODEL
# - OPENROUTER_BASE_URL
# - ERPNEXT_API_KEY
# - ERPNEXT_API_SECRET
# - ERPNEXT_BASE_URL

# Build configuration
[build]
command = "npm run build"

# Development
[dev]
port = 3000
