# Wrangler configuration for Frontend (Cloudflare Pages)
name = "erpnext-coagent-ui"
account_id = "5a34e22d045e4ff3538a636317a631e8"
compatibility_date = "2024-10-01"
pages_build_output_dir = "dist"

# Build command (runs during deployment)
[build]
command = "npm run build"

# Environment variables for build
[vars]
VITE_GATEWAY_URL = "https://erpnext-agent-gateway.workers.dev"

# Development
[dev]
port = 5173
